const state={data:null,selected:null,query:"",risk:"all",horizon:"14",collapsed:{}};

function fmtPct(v){if(v===null||v===undefined||Number.isNaN(v)) return "—"; return `${(v*100).toFixed(1)}%`;}
function explainLabel(v){if(v>=0.75) return "очень высокий"; if(v>=0.55) return "повышенный"; if(v>=0.35) return "умеренный"; return "низкий";}
function activeRisk(w){return state.horizon==="14"?(w.risk14d??0):(w.risk90d??0)}
function activePred(w){return state.horizon==="14"?w.pred14d:w.pred90d}
function activeDrivers(w){return state.horizon==="14"?(w.drivers14d||[]):(w.drivers90d||[])}
function activeGroups(w){return state.horizon==="14"?(w.groupDrivers14d||[]):(w.groupDrivers90d||[])}

function activeShap(w){return state.horizon==="14"?(w.shap14d||[]):(w.shap90d||[])}
function shapCard(item){const sign=(item.value??0)>=0?'+':''; return `<div class="driver-item shap-item"><div class="topline"><strong>${item.feature??'—'}</strong><span class="shap-value ${(item.value??0)>=0?'pos':'neg'}">${sign}${Number(item.value??0).toFixed(4)}</span></div><small>${item.prettyValue??''}</small></div>`}


function showFatalError(message, details=""){const content=document.querySelector('.content'); if(!content) return; content.innerHTML=`<section class="card" style="border:1px solid #f2b8b5; background:#fff7f7;"><h2 style="margin-bottom:10px; color:#b42318;">Ошибка загрузки данных</h2><p style="margin-bottom:10px; color:#344054;">${message}</p>${details?`<pre style="white-space:pre-wrap; background:#fff; padding:12px; border-radius:12px; border:1px solid #ead7d7; color:#7a271a;">${details}</pre>`:""}</section>`;}

function renderSummary(){const s=state.data.summary; document.getElementById('summaryCards').innerHTML=`<div class="mini-card"><span>Всего вагонов</span><strong>${s.totalWagons??'—'}</strong></div><div class="mini-card"><span>Локаций</span><strong>${s.locations??'—'}</strong></div><div class="mini-card"><span>Высокий риск 14д</span><strong>${s.highRisk14d??'—'}</strong></div><div class="mini-card"><span>Высокий риск 90д</span><strong>${s.highRisk90d??'—'}</strong></div>`;}

function groupedWagons(){let wagons=state.data.wagons.filter(w=>{const q=state.query.toLowerCase(); const wagonId=String(w.wagonId??'').toLowerCase(); const location=String(w.location??'').toLowerCase(); const matchesQ=!q||wagonId.includes(q)||location.includes(q); const matchesRisk=state.risk==='all'||w.riskLevel===state.risk; return matchesQ&&matchesRisk;}); const groups={}; for(const w of wagons){const location=w.location||'Неизвестная локация'; if(!groups[location]) groups[location]=[]; groups[location].push(w);} return Object.entries(groups).sort((a,b)=>b[1].length-a[1].length);}

function toggleLocation(location){state.collapsed[location]=!state.collapsed[location]; renderLocations();}

function renderLocations(){const root=document.getElementById('locationList'); root.innerHTML=''; const groups=groupedWagons(); if(!groups.length){root.innerHTML='<div class="location-group"><div class="muted">Нет вагонов по текущему фильтру.</div></div>'; return;} for(const [location,wagons] of groups){const group=document.createElement('div'); group.className='location-group'+(state.collapsed[location]?' collapsed':''); const header=document.createElement('div'); header.className='location-header'; header.innerHTML=`<div class="location-header-left"><span class="collapse-icon">▾</span><h3>${location}</h3></div><span class="count-badge">${wagons.length} вагонов</span>`; header.onclick=()=>toggleLocation(location); group.appendChild(header); const items=document.createElement('div'); items.className='wagon-items'; wagons.sort((a,b)=>activeRisk(b)-activeRisk(a)); wagons.forEach(w=>{const btn=document.createElement('button'); btn.className='wagon-item'+(state.selected&&state.selected.wagonId===w.wagonId?' active':''); btn.innerHTML=`<div class="wagon-top"><span class="wagon-id">${w.wagonId??'—'}</span><span class="risk-chip ${w.riskLevel??'Low'}">${w.riskLevel??'Low'}</span></div><div class="wagon-meta"><span>${state.horizon==='14'?'14д':'90д'} ${fmtPct(activeRisk(w))}</span></div>`; btn.onclick=()=>selectWagon(w.wagonId); items.appendChild(btn);}); group.appendChild(items); root.appendChild(group);} }

function selectWagon(id){state.selected=state.data.wagons.find(w=>w.wagonId===id)||null; renderLocations(); renderDetails();}
function kv(label,value){return `<div class="kv-row"><span>${label}</span><span>${value??'—'}</span></div>`}
function driverCard(item){return `<div class="driver-item"><div class="topline"><strong>${item.feature??'—'}</strong></div><small>${item.value??''}</small></div>`}
function groupCard(item){return `<div class="group-item"><div class="topline"><strong>${item.group??'—'}</strong></div></div>`}

function buildNarrative(w){const risk=activeRisk(w); const drivers=activeDrivers(w); const groups=activeGroups(w); const horizonLabel=state.horizon==='14'?'14 дней':'90 дней'; if(!drivers.length&&!groups.length){return `<div class="explain-box"><div class="explain-title">Почему такой прогноз</div><p class="muted">Модель оценивает риск как <strong>${explainLabel(risk)}</strong>, но для этой записи нет прикрепленного объяснения факторов.</p></div>`;} const topDriverNames=drivers.slice(0,3).map(d=>d.feature).join(', '); const topGroups=groups.slice(0,3).map(g=>g.group).join(', '); return `<div class="explain-box"><div class="explain-title">Почему такой прогноз</div><p class="explain-text">Для горизонта <strong>${horizonLabel}</strong> модель оценивает <strong>${explainLabel(risk)}</strong> вероятность поломки (${fmtPct(risk)}).</p><p class="explain-text">Главные факторы для этого вагона: <strong>${topDriverNames||'нет доступных индивидуальных факторов'}</strong>.</p><p class="explain-text">На уровне групп сильнее всего влияют: <strong>${topGroups||'нет доступных групп факторов'}</strong>.</p></div>`;}

function renderDetails(){const w=state.selected; const horizonLabel=state.horizon==='14'?'14 дней':'90 дней'; document.getElementById('riskBlockTitle').textContent=`Прогноз риска · ${horizonLabel}`; document.getElementById('factorsTitle').textContent=`Факторы риска · ${horizonLabel}`; if(!w){document.getElementById('wagonTitle').textContent='Выберите вагон'; document.getElementById('wagonSubtitle').textContent='Нажмите на вагон слева, чтобы посмотреть прогноз и факторы риска.'; document.getElementById('riskMain').textContent='—'; document.getElementById('predMain').textContent='—'; document.getElementById('contextList').innerHTML=''; document.getElementById('driversMain').innerHTML=''; document.getElementById('groupsMain').innerHTML=''; document.getElementById('profileGrid').innerHTML=''; return;} document.getElementById('wagonTitle').textContent=w.wagonId??'—'; document.getElementById('wagonSubtitle').textContent=String(w.location??'—'); document.getElementById('riskLabel').textContent=`Вероятность поломки (${horizonLabel})`; document.getElementById('predLabel').textContent=`Класс прогноза (${horizonLabel})`; document.getElementById('riskMain').textContent=fmtPct(activeRisk(w)); document.getElementById('predMain').textContent=activePred(w)?'Поломка вероятна':'Низкий риск'; document.getElementById('contextList').innerHTML=[kv('Текущая локация', w.location),kv('Страна отправления', w.countryFrom),kv('Страна назначения', w.countryTo),kv('Погода', w.weather),kv('Температура', w.temperature===null||w.temperature===undefined?'—':`${w.temperature} °C`),kv('Скорость ветра', w.windSpeed===null||w.windSpeed===undefined?'—':`${w.windSpeed} м/с`)].join(''); const profileEntries=Object.entries(w.profile||{}).filter(([k,v])=>!String(k).toLowerCase().includes('ремонт')); document.getElementById('profileGrid').innerHTML=profileEntries.map(([k,v])=>`<div class="profile-item"><span>${k}</span><strong>${v??'—'}</strong></div>`).join(''); const drivers=activeDrivers(w); const groups=activeGroups(w); const shapItems=activeShap(w); document.getElementById('driversMain').innerHTML=buildNarrative(w)+(drivers.length?drivers.filter(d=>!String(d.feature).toLowerCase().includes('ремонт') && !String(d.feature).toLowerCase().includes('назнач')).map(driverCard).join(''):'<p class="muted">Нет прикрепленных факторов.</p>'); document.getElementById('shapMain').innerHTML=shapItems.length?shapItems.map(shapCard).join(''):'<p class="muted">SHAP-пояснения еще не добавлены в JSON.</p>'; document.getElementById('groupsMain').innerHTML=groups.length?groups.map(groupCard).join(''):'<p class="muted">Нет прикрепленных групп факторов.</p>';}

async function loadData(){try{const res=await fetch('wagons_data.json',{cache:'no-store'}); if(!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`); const data=await res.json(); if(!data||typeof data!=='object') throw new Error('JSON пустой или невалидный.'); if(!data.summary||!Array.isArray(data.wagons)) throw new Error('В JSON должны быть ключи summary и wagons.'); state.data=data; const noteEl=document.getElementById('noteText'); if(noteEl) noteEl.textContent=state.data.summary.notes||''; renderSummary(); renderLocations(); if(state.data.wagons.length){selectWagon(state.data.wagons[0].wagonId);} else {renderDetails(); showFatalError('JSON загружен, но массив wagons пустой.');}}catch(err){console.error('Failed to load wagons_data.json:',err); showFatalError('Интерфейс не смог загрузить wagons_data.json.', String(err));}}

window.addEventListener('DOMContentLoaded',()=>{const search=document.getElementById('searchInput'); const filter=document.getElementById('riskFilter'); if(search){search.addEventListener('input',e=>{state.query=e.target.value; renderLocations();});} if(filter){filter.addEventListener('change',e=>{state.risk=e.target.value; renderLocations();});} document.querySelectorAll('.toggle-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.toggle-btn').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); state.horizon=btn.dataset.horizon; renderLocations(); renderDetails();})); loadData();});
